// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// AlphaPartDrop
List AlphaPartDrop(double c1, double c2, int nI, int nP, int nT, NumericMatrix ped, IntegerVector P, IntegerVector Px);
RcppExport SEXP _AlphaPart_AlphaPartDrop(SEXP c1SEXP, SEXP c2SEXP, SEXP nISEXP, SEXP nPSEXP, SEXP nTSEXP, SEXP pedSEXP, SEXP PSEXP, SEXP PxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type c2(c2SEXP);
    Rcpp::traits::input_parameter< int >::type nI(nISEXP);
    Rcpp::traits::input_parameter< int >::type nP(nPSEXP);
    Rcpp::traits::input_parameter< int >::type nT(nTSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ped(pedSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type P(PSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Px(PxSEXP);
    rcpp_result_gen = Rcpp::wrap(AlphaPartDrop(c1, c2, nI, nP, nT, ped, P, Px));
    return rcpp_result_gen;
END_RCPP
}
// AlphaPartDropGroup
NumericMatrix AlphaPartDropGroup(double c1, double c2, int nI, int nP, int nT, int nG, NumericMatrix ped, IntegerVector P, IntegerVector Px, IntegerVector g);
RcppExport SEXP _AlphaPart_AlphaPartDropGroup(SEXP c1SEXP, SEXP c2SEXP, SEXP nISEXP, SEXP nPSEXP, SEXP nTSEXP, SEXP nGSEXP, SEXP pedSEXP, SEXP PSEXP, SEXP PxSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type c2(c2SEXP);
    Rcpp::traits::input_parameter< int >::type nI(nISEXP);
    Rcpp::traits::input_parameter< int >::type nP(nPSEXP);
    Rcpp::traits::input_parameter< int >::type nT(nTSEXP);
    Rcpp::traits::input_parameter< int >::type nG(nGSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ped(pedSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type P(PSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Px(PxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(AlphaPartDropGroup(c1, c2, nI, nP, nT, nG, ped, P, Px, g));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AlphaPart_AlphaPartDrop", (DL_FUNC) &_AlphaPart_AlphaPartDrop, 8},
    {"_AlphaPart_AlphaPartDropGroup", (DL_FUNC) &_AlphaPart_AlphaPartDropGroup, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_AlphaPart(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
